---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deploy
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: app
        tier: frontend
    spec:
      containers:
        - name: app-golang
          image: asia.gcr.io/idyllic-depth-239301/tech-test2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 10000
          resources:
            requests:
              cpu: 50m
              memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: app
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 10000
